### ISSUE TITLE
Desktop agent lists projects whose tasks the API then refuses

### ISSUE THREAD

**Issue by Lamakira** [Lamakira/docuflow#31]
## Symptom

The agent logs a run of identical refusals, one per project the picker touches:

```
[ApiClient] Forbidden (403, not a revocation): Access denied
```

The device is not revoked and the session is healthy — heartbeat, timer resync and the workers all run normally. Only task reads fail.

## Cause

Two endpoints disagree about who may see a CRM project.

- `GET /api/agent/projects` (`server/agentRoutes.ts:953`) returns `storage.getCrmProjects(userId)` — everything the user can *see*.
- `GET /api/agent/tasks` (`server/agentRoutes.ts:886`) requires membership:

  ```ts
  const isMember =
    crmProject.members.some((m: any) => m.userId === userId) ||
    crmProject.project?.ownerId === userId;
  if (!isMember) return res.status(403).json({ message: "Access denied" });
  ```

So the picker lists a project, the user opens it, and the follow-up task read is denied every time. The same check guards `POST /api/agent/tasks` (`:931`) and `POST /api/agent/timer/start` (`:1016`), which means a listed project can also be impossible to *start a timer on* — the refusal is not limited to a cosmetic task count.

The agent already knows this happens and works around it rather than fixing it: `desktop-agent/src/renderer/app-v2/panels/TimerPanel.tsx:60` documents "the project list can include projects this user is not a member of" and suppresses the retry, and `desktop-agent/src/lib/ApiClient.ts:451` special-cases the 403 so a non-membership refusal is not mistaken for device revocation.

## Reproduce

1. Sign a desktop agent in as a user who can see a CRM project but holds no membership row on it and does not own it.
2. Open that project in the picker.
3. `GET /api/agent/tasks?crmProjectId=<id>` → 403 `Access denied`; the log line repeats once per project viewed.

The log now names the route and project id (`GET /api/agent/tasks?crmProjectId=… — Access denied`), so the offending project is identifiable from a run.

## The decision this needs

Which endpoint is wrong is a product question, not a mechanical one:

- **Tighten the list** — `/api/agent/projects` returns only projects the user is a member of or owns. The picker stops offering what it cannot open. Changes what the agent shows to existing users.
- **Loosen the guard** — visibility is enough to read tasks and start a timer. Widens who can log time against a project.
- **Show it, mark it** — keep both, and have the list flag the projects the user cannot track against, so the refusal is expected rather than silent.

## Scope note

`/api/agent/tasks` and `/api/agent/timer/start` are frozen by the desktop v1 protocol characterization suite (#21) — `tests/characterization/agent-workspace.test.ts` and `agent-timer.test.ts`. Whichever option is chosen, those suites encode the current behavior and must move with it deliberately, since a contract change there is exactly what they exist to catch.

**Comment by Lamakira** [comment]
Heads-up from #25: the predicate this issue quotes has moved, and one thing about it changed. The policy question is untouched and still yours.

**It now lives in one place.** `server/agentRoutes.ts` had the same two lines written out three times, at the task list, the task create, and the timer start. They are now one function:

```ts
function canActOnCrmProject(crmProject: CrmProjectWithDetails, userId: string): boolean {
  return (
    crmProject.members?.some((m) => m.userId === userId) === true ||
    crmProject.project?.ownerId === userId
  );
}
```

Whichever option this issue picks — tighten the list, loosen the guard, show-and-mark — it is one edit now instead of three that could drift apart. Its doc comment names this issue as the owner of the policy, and names the characterization suites (#21) that freeze the current answer.

**`members` gained an optional chain, and that is type-narrowing only.** #25 added a typecheck step to CI, which failed on `main`: `members` is optional on `CrmProjectWithDetails` (TS18048, three times). The guard now reads `members?.some(...)`, so an absent `members` denies rather than throwing. No runtime behaviour changed — `storage.getCrmProject` always populates `members` — so this is not a vote for the "loosen the guard" option or against it. If this issue lands on loosening, that is still a live change to make here.
